[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install && npm install --save-dev @types/express @types/cors"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/http-entry.js"