[build]
builder = "nixpacks"
buildCommand = "npm install && npm install --save-dev @types/express @types/cors && npm run build"

[deploy]
startCommand = "node --max-old-space-size=512 dist/railway-wrapper.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
protocol = "tcp"
port = 3000

[variables]
NODE_ENV = "production"
USE_HTTP_SERVER = "true"
