services:
  - type: web
    name: mcp-multi-api-server
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    buildCommand: npm install && npm run build:render
    startCommand: node dist/http-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true